function roboPlot(data)
  
% Plot the data generated by measureRobo
%
%
  
clf  
col=jet(length(data));
for ii=1:length(data)
  subplot(1,2,1)
  hold on
  plot(smooth(data(ii).oct,100),'color',col(ii,:))
  plotAir
  hold off
  title('octanol')

  
  
  subplot(1,2,2)
  hold on
  plot(smooth(data(ii).mch,100),'color',col(ii,:))
  plotAir
  hold off
  title('MCH')  
end
makeAxesEqual


function plotAir
  if isfield(data,'air')
    plot(mean([data.air],2),'-g')
  end
end
  

end
  
